[mypy]
strict = True
python_version = 3.12
namespace_packages = True
explicit_package_bases = True
mypy_path = services/app:packages/models:packages/ingest:packages/ingest/tests:packages/verify:packages/verify/tests
plugins = pydantic.mypy

[mypy-pypdfium2.*]
ignore_missing_imports = True

[mypy-olefile.*]
ignore_missing_imports = True
